services:
  - type: web
    name: whatsapp-pairing
    env: node
    plan: free
    branch: main
    repo: https://github.com/DEDSEC812/SESSION-ID
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
