services:
  - type: web
    name: ORMAN-XMD-pair-site
    env: docker
    plan: free
    branch: main
    repo: https://github.com/Orman87/ORMAN-XMD
    dockerfilePath: ./Dockerfile
    autoDeploy: true
